export const datatableConstants = {
    CREATE_REQUEST: 'DT_CREATE_REQUEST',
    CREATE_SUCCESS: 'DT_CREATE_SUCCESS',
    CREATE_FAILURE: 'DT_CREATE_FAILURE',

    UPDATE_REQUEST: 'DT_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'DT_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'DT_UPDATE_FAILURE',

    GET_ALL_REQUEST: 'DT_GET_ALL_REQUEST',
    GET_ALL_SUCCESS: 'DT_GET_ALL_SUCCESS',
    GET_ALL_FAILURE: 'DT_GET_ALL_FAILURE',

    TOGGLE_MODAL: 'DT_TOGGLE_MODAL',

    FILTER_REQUEST: 'DT_FILTER_REQUEST',
    FILTER_SUCCESS: 'DT_FILTER_SUCCESS',
    FILTER_FAILURE: 'DT_FILTER_FAILURE',

    DELETE_REQUEST: 'DT_DELETE_REQUEST',
    DELETE_SUCCESS: 'DT_DELETE_SUCCESS',
    DELETE_FAILURE: 'DT_DELETE_FAILURE'
};
