export const leaveConstants = {
    CREATE_REQUEST: 'LEAVE_CREATE_REQUEST',
    CREATE_SUCCESS: 'LEAVE_CREATE_SUCCESS',
    CREATE_FAILURE: 'LEAVE_CREATE_FAILURE',

    UPDATE_REQUEST: 'LEAVE_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'LEAVE_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'LEAVE_UPDATE_FAILURE',

    GET_ALL_REQUEST: 'LEAVE_GET_ALL_REQUEST',
    GET_ALL_SUCCESS: 'LEAVE_GET_ALL_SUCCESS',
    GET_ALL_FAILURE: 'LEAVE_GET_ALL_FAILURE',

    READ_REQUEST: 'LEAVE_READ_REQUEST',
    READ_SUCCESS: 'LEAVE_READ_SUCCESS',
    READ_FAILURE: 'LEAVE_READ_FAILURE',

    DELETE_REQUEST: 'LEAVE_DELETE_REQUEST',
    DELETE_SUCCESS: 'LEAVE_DELETE_SUCCESS',
    DELETE_FAILURE: 'LEAVE_DELETE_FAILURE'
};
