export const leaveConstants = {
    CREATE_REQUEST: 'LEAVES_CREATE_REQUEST',
    CREATE_SUCCESS: 'LEAVES_CREATE_SUCCESS',
    CREATE_FAILURE: 'LEAVES_CREATE_FAILURE',

    UPDATE_REQUEST: 'LEAVES_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'LEAVES_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'LEAVES_UPDATE_FAILURE',

    GET_ALL_REQUEST: 'LEAVES_GET_ALL_REQUEST',
    GET_ALL_SUCCESS: 'LEAVES_GET_ALL_SUCCESS',
    GET_ALL_FAILURE: 'LEAVES_GET_ALL_FAILURE',

    READ_REQUEST: 'LEAVES_READ_REQUEST',
    READ_SUCCESS: 'LEAVES_READ_SUCCESS',
    READ_FAILURE: 'LEAVES_READ_FAILURE',

    DELETE_REQUEST: 'LEAVES_DELETE_REQUEST',
    DELETE_SUCCESS: 'LEAVES_DELETE_SUCCESS',
    DELETE_FAILURE: 'LEAVES_DELETE_FAILURE'
};
