export const userConstants = {
    CREATE_REQUEST: 'USER_CREATE_REQUEST',
    CREATE_SUCCESS: 'USER_CREATE_SUCCESS',
    CREATE_FAILURE: 'USER_CREATE_FAILURE',

    UPDATE_REQUEST: 'USER_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'USER_UPDATE_FAILURE',

    GET_ALL_REQUEST: 'USER_GET_ALL_REQUEST',
    GET_ALL_SUCCESS: 'USER_GET_ALL_SUCCESS',
    GET_ALL_FAILURE: 'USER_GET_ALL_FAILURE',

    READ_REQUEST: 'USER_READ_REQUEST',
    READ_SUCCESS: 'USER_READ_SUCCESS',
    READ_FAILURE: 'USER_READ_FAILURE',

    DELETE_REQUEST: 'USER_DELETE_REQUEST',
    DELETE_SUCCESS: 'USER_DELETE_SUCCESS',
    DELETE_FAILURE: 'USER_DELETE_FAILURE'
};
